"""Session tokens minted at the edge, and what they entitle someone to."""

import time

import pytest

from tmo.payments import session as S
from tmo.payments.store import SubscriberStore

SECRET = "a-secret-that-is-long-enough-to-be-a-secret"
NOW = 1_800_000_000


def claims(**over):
    base = {"sub": "google-1", "email": "someone@example.com", "email_verified": True,
            "name": "Someone", "iat": NOW, "exp": NOW + 3600}
    base.update(over)
    return base


@pytest.fixture
def store(tmp_path):
    return SubscriberStore(str(tmp_path / "s.json"), cache_ttl_s=0)


# ── the token ──────────────────────────────────────────────────────────────
def test_a_good_token_verifies():
    i = S.verify(S.sign(claims(), SECRET), SECRET, now=NOW)
    assert i.sub == "google-1" and i.email == "someone@example.com"


def test_a_token_signed_with_another_secret_is_refused():
    t = S.sign(claims(), "a-completely-different-secret")
    with pytest.raises(S.SessionError, match="signature"):
        S.verify(t, SECRET, now=NOW)


def test_a_tampered_payload_is_refused():
    t = S.sign(claims(), SECRET)
    payload, sig = t.split(".")
    forged = S._b64url_encode(b'{"sub":"x","email":"attacker@evil.com","exp":99999999999}')
    with pytest.raises(S.SessionError, match="signature"):
        S.verify(f"{forged}.{sig}", SECRET, now=NOW)


def test_an_expired_session_is_refused():
    t = S.sign(claims(), SECRET)
    with pytest.raises(S.SessionError, match="expired"):
        S.verify(t, SECRET, now=NOW + 3601)


def test_an_unverified_email_is_refused_because_entitlement_matches_on_it():
    t = S.sign(claims(email_verified=False), SECRET)
    with pytest.raises(S.SessionError, match="not verified"):
        S.verify(t, SECRET, now=NOW)


@pytest.mark.parametrize("junk", ["", None, "abc", "a.b.c", "."])
def test_junk_is_refused_without_raising_something_else(junk):
    with pytest.raises(S.SessionError):
        S.verify(junk, SECRET, now=NOW)


def test_no_secret_means_no_session():
    with pytest.raises(S.SessionError, match="no session secret"):
        S.verify(S.sign(claims(), SECRET), "", now=NOW)


def test_a_token_minted_by_the_edge_verifies_here():
    """Pinned output of web/lib/token.ts, generated by its own code.

    The edge mints and this side verifies, in two languages, so the formats can
    drift apart without either side's own tests noticing. This is the seam, and
    it fails here rather than silently signing nobody in.
    """
    token = ("eyJzdWIiOiJnb29nbGUtMSIsImVtYWlsIjoic29tZW9uZUBleGFtcGxlLmNvbSIsImVtYWlsX3Zl"
             "cmlmaWVkIjp0cnVlLCJuYW1lIjoiU29tZW9uZSIsImlhdCI6MTgwMDAwMDAwMCwiZXhwIjoxODAw"
             "MDAzNjAwfQ.jUe30huMqIWDLGhNr3pRFDtIzjW8VsJ1EGFvvDVVbD4")
    identity = S.verify(token, SECRET, now=NOW)
    assert identity.sub == "google-1"
    assert identity.email == "someone@example.com"
    assert identity.name == "Someone"
    assert identity.expires_at == NOW + 3600


def test_this_side_and_the_edge_agree_on_the_bytes():
    """Signing the same claims here must reproduce the edge's token exactly."""
    mine = S.sign({"sub": "google-1", "email": "someone@example.com",
                   "email_verified": True, "name": "Someone",
                   "iat": 1800000000, "exp": 1800003600}, SECRET)
    assert mine == ("eyJzdWIiOiJnb29nbGUtMSIsImVtYWlsIjoic29tZW9uZUBleGFtcGxlLmNvbSIsImVtYWlsX3Zl"
                    "cmlmaWVkIjp0cnVlLCJuYW1lIjoiU29tZW9uZSIsImlhdCI6MTgwMDAwMDAwMCwiZXhwIjoxODAw"
                    "MDAzNjAwfQ.jUe30huMqIWDLGhNr3pRFDtIzjW8VsJ1EGFvvDVVbD4")


# ── entitlement ────────────────────────────────────────────────────────────
def test_a_paying_subscriber_signing_in_as_themselves_is_entitled(store):
    store.set_active("sub_1", active=True, tier="terminal", email="someone@example.com")
    e = S.entitlement_for(S.verify(S.sign(claims(), SECRET), SECRET, now=NOW), store, now=NOW)
    assert e.entitled and e.tier == "terminal" and e.subscription_id == "sub_1"


def test_matching_on_email_ignores_case(store):
    store.set_active("sub_1", active=True, tier="terminal", email="SomeOne@Example.COM")
    e = S.entitlement_for(S.verify(S.sign(claims(), SECRET), SECRET, now=NOW), store, now=NOW)
    assert e.entitled


def test_an_unknown_account_is_offered_the_chance_to_link(store):
    e = S.entitlement_for(S.verify(S.sign(claims(), SECRET), SECRET, now=NOW), store, now=NOW)
    assert not e.entitled and e.needs_link
    assert "no subscription" in e.reason


def test_paying_with_one_address_and_signing_in_with_another(store):
    store.set_active("sub_1", active=True, tier="terminal", email="work@example.com")
    identity = S.verify(S.sign(claims(email="personal@example.com"), SECRET), SECRET, now=NOW)
    assert S.entitlement_for(identity, store, now=NOW).needs_link
    assert store.link_identity("sub_1", identity.sub)
    e = S.entitlement_for(identity, store, now=NOW)
    assert e.entitled and e.subscription_id == "sub_1"


def test_linking_is_idempotent_and_allows_a_second_account(store):
    store.set_active("sub_1", active=True, tier="terminal", email="work@example.com")
    store.link_identity("sub_1", "google-1")
    store.link_identity("sub_1", "google-1")
    store.link_identity("sub_1", "google-2")
    assert store.get("sub_1")["identities"] == ["google-1", "google-2"]


def test_linking_an_unknown_subscription_fails_rather_than_inventing_one(store):
    assert store.link_identity("sub_nobody", "google-1") is False
    assert store.get("sub_nobody") is None


def test_a_linked_account_survives_the_email_changing(store):
    store.set_active("sub_1", active=True, tier="terminal", email="old@example.com")
    store.link_identity("sub_1", "google-1")
    store.set_active("sub_1", active=True, tier="terminal", email="new@example.com")
    identity = S.verify(S.sign(claims(email="anything@example.com"), SECRET), SECRET, now=NOW)
    assert S.entitlement_for(identity, store, now=NOW).entitled


def test_a_refunded_subscriber_is_recognised_but_not_entitled(store):
    store.set_active("sub_1", active=True, tier="terminal", email="someone@example.com")
    store.set_active("sub_1", active=False, tier="terminal", expires_at=NOW - 1)
    e = S.entitlement_for(S.verify(S.sign(claims(), SECRET), SECRET, now=NOW), store, now=NOW)
    assert not e.entitled and not e.needs_link
    assert e.reason == "the subscription is not active"


def test_a_cancelled_subscriber_keeps_access_through_the_paid_period(store):
    store.set_active("sub_1", active=True, tier="terminal", email="someone@example.com")
    store.set_active("sub_1", active=False, active_until=NOW + 86400)
    identity = S.verify(S.sign(claims(), SECRET), SECRET, now=NOW)
    assert S.entitlement_for(identity, store, now=NOW).entitled
    assert not S.entitlement_for(identity, store, now=NOW + 86401).entitled


def test_the_most_recently_updated_record_wins_for_a_resubscriber(store):
    store.set_active("old", active=False, tier="terminal", email="someone@example.com")
    time.sleep(0.01)
    store.set_active("new", active=True, tier="terminal", email="someone@example.com")
    e = S.entitlement_for(S.verify(S.sign(claims(), SECRET), SECRET, now=NOW), store, now=NOW)
    assert e.subscription_id == "new" and e.entitled
